name: Run gulp tasks

# Controls when the action will run.
on:
  push:
    # On which branch
    branches: ["develop"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - run: npm install
      - run: gulp
            
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add --all
          git commit -m "Built By Gulp"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          force: true
